### ISSUE TITLE
访问级别default或者package可能比friendly更好一些

### ISSUE THREAD

**Issue by jywangkeep** [waylau/essential-java#4]
对于访问级别`friendly`，可能`default`或者`package`更好一些。如果使用`package`则说明本包内部以及自身可以使用，个人觉得这样可能语义上更加清晰。

**Comment by waylau** [comment]
@jywangkeep   friendly 或 default 在相关的书籍中都有类似的表述，都是 默认访问级别的代名词。考虑读者的习惯，我将两者都添加到了文中。

感谢您的反馈！
