### ISSUE TITLE
关于更加完善的问题

### ISSUE THREAD

**Issue by qcxiao** [waylau/essential-java#8]
目前我大致浏览了一遍，发现很多地方还不够完善；比如JDBC相关的还没有写、泛型部分至少应该谈一谈entends和super的关系等。不过已经很赞了，希望继续完善。

**Comment by waylau** [comment]
@qcxiao  感谢反馈!

JDBC的内容已经单独开了课程，见 https://github.com/waylau/jdbc-specification

**Comment by waylau** [comment]
@qcxiao 泛型相关的内容已经做了补充
